### ISSUE TITLE
Please Add Deploy Option to Railway.app cause Heroku free is going to shut down in 2022

### ISSUE THREAD

**Issue by lstprjctheroku** [wahyd4/aria2-ariang-docker#184]
Please Add Deploy Option to Railway.app cause Heroku free is going to shut down in 2022
@wahyd4

**Comment by wahyd4** [comment]
Hi @lstprjctheroku at this moment, I have no plan to support this, I probably will leave it here for a while to see if anyone else have similar demands of using railway.app. Meanwhile, if you really want this happen, you can consider sponsoring developing this feature.

**Comment by abhishekhbhootwala** [comment]
@wahyd4 I was also thinking the same thing. If possible please add an option for railway.app @lstprjctheroku thanks mate for your concern.

**Comment by wahyd4** [comment]
Hi guys, can you share the news which says Heroku is going to shut down the free tier in 2022? I couldn't find it.

**Comment by torrentleeching** [comment]
Please Add Deploy Option to okteto

**Comment by wahyd4** [comment]
Hi all, not sure if you have seen this recent issue https://github.com/wahyd4/aria2-ariang-docker/issues/204, which showed Heroku blocks this app. I don't know the exact reason, but maybe it's because some people are running this docker image on Heroku and downloading illegal media files.

Based on that, I decided to not add any official support to run this docker image on other platforms. 
You are fine to clone this repo and implement it by yourself.
