### ISSUE TITLE
How to change File Manager Root directory?

### ISSUE THREAD

**Issue by fanyh123** [wahyd4/aria2-ariang-docker#19]
Hi,I hope change File Manager Root directory different from aria2 dowloads directory. because I want Manager more files instead of only  aria2 dowloads directory. Thanks a lot

**Comment by wahyd4** [comment]
Currently, you can not change the root folder configuration from the command line. But I'm happy to make this configuration to be configurable through the environment variables, but due to the latest version of `filemanager` is broken, so I can not build a new Docker image without upgrading `filemanager`.

Anyway, there is a workaround which is you can modify the download file path for `aria2c` through AriaNg, then the folders are different and can be whatever folders you like.

**Comment by fanyh123** [comment]
Ok. I got it. Thanks a lot.
