### ISSUE TITLE
ARIA2 AND BITTORRENT ADD PATH

### ISSUE THREAD

**Issue by rinrinx** [wahyd4/aria2-ariang-docker#199]
Can you directly connect the files downloaded with aria2 to any cloud in rclone for downloading?

Direct download cloud aria2 and bittorrent

**Comment by kamileecher2** [comment]
For example, aria2 should be uploaded directly to rclo clouds when you download it, so it would be great if you add it.conf feature

**Comment by wahyd4** [comment]
Thanks for the clarification, unfortunately, I don't have a good solution now to implement this feature with a smooth user experience while without or having very limited user input.

**Comment by lopho27** [comment]
I have experience about using rclone with aria2 + NG, the feature is completely crazy, you can remote upload directly to your cloud ( gdrive etc ) and run in background at cloud service in heroku but now the account has been suspended a few days ago.. because the rule of app usage policy of heroku.. how they detect me, because i just detected a few days ago after long time use ariaNG on heroku. People got many suspended their account far behind from me..in early 2021. I got banned in May 2022. Now i will implement it with docker and raspberry. Its my first time using raspberry

**Comment by wahyd4** [comment]
@rinrinx as of the latest version, we officially support auto uploading downloaded files to remote Cloud via Rclone, please check the readme for instructions.
