### ISSUE TITLE
DHT files can't be found in path of /root/.cache/aria2/dht.dat

### ISSUE THREAD

**Issue by duanyu5871** [wahyd4/aria2-ariang-docker#210]
## Please try to use English to describe your question or issue.

**Describe the bug**
DHT files was located in /root/.cache/aria2/dht.dat or /root/.cache/aria2/dht6.dat in ariang settings which cannot move.
When I download some BT files and comfired the DHT should be established,  there is still noting in docker container.

**Screenshots**
![K~5U%D2T}Y}GHZYKWMFR8$W](https://user-images.githubusercontent.com/15108185/163698135-518aae81-9c26-4c3a-a38a-8124ffe65327.png)

**Comment by wahyd4** [comment]
Hi @duanyu5871 thanks for reporting this error.

So long story short, the issue was because the program doesn't have permission to write files to `/root` folder.  Now I have moved the `dht.dat` file to `/app` folder in the aria2 default configuration. If you need support for ipv6 version, please use your custom `aria2.conf` file. 

You will still see error messages saying `"Failed to load DHT routing table from xxx"` when you start downloading something after you start the container. But aria2 will ##create## a new dht.dat file after `30 minutes`, and constantly update that file every 30 minutes. So you can just ignore that error

For more details, please check https://github.com/wahyd4/aria2-ariang-docker/pull/211


To solve this issue, all you need to do is just re-pull the latest docker image. Let me know if this issue still exist.

**Comment by duanyu5871** [comment]
@wahyd4 
Thanks a lot, new version has worked. 
And before your update, my solution is to create volume in docker for `/root/.cache/aria2/` folder and pre-built a blank DHT file which has writeable permission for docker user.
