### ISSUE TITLE
容器无法启动

### ISSUE THREAD

**Issue by gitby2018** [wahyd4/aria2-ariang-docker#30]
用教程里的这个命令进行修改以后，启动容器就自动停止了，无法启动起来，删掉一些参数也无法启动。不知道什么原因。
docker run -d --name ariang \
  -p 80:80 -p 6800:6800 -p 443:443 \
  -e ENABLE_AUTH=true \
  -e RPC_SECRET=Hello \
  -e DOMAIN=example.com \
  -e ARIA2_USER=user \
  -e ARIA2_PWD=pwd \
  -v /yourdata:/data \
  -v /root/a.db:/root/filebrowser.db \
  -v /yoursslkeys/:/root/conf/key \
  -v <to your aria2.conf>:/root/conf/aria2.conf \
  wahyd4/aria2-ui

**Comment by wahyd4** [comment]
Please paste the error log of the container, so we can know what's the error.

**Comment by gitby2018** [comment]
我修改成
docker run -d --name ariang \
  -p 8980:80 -p 8988:6800 -p 8989:443 \
  -e ENABLE_AUTH=true \
  -e RPC_SECRET=uoley \
  -e DOMAIN=my domain\
  -e ARIA2_USER=user \
  -e ARIA2_PWD=pwd_3459 \
  -v /home/app/aria2/data:/data \
  -v /home/app/aria2/filebrowser/a.db:/root/filebrowser.db \
  -v /home/app/aria2/conf/key:/root/conf/key \
  -v /home/app/aria2/conf:/root/conf \
  wahyd4/aria2-ui

**Comment by gitby2018** [comment]
我不知道怎么查看error log

**Comment by wahyd4** [comment]
You should learn some docker stuff first. Anyway there is another way to see the error logs which is run the same  command but without ` -d`. This command will run the application in the current thread not the background. Then you should see the error logs.

By the way, I guess the issue might be because there are some configurations are wrong, maybe you should start with the most simple command then gradually add more options and configurations.

**Comment by wahyd4** [comment]
@gitby2018 Since there are no further updates, I will close his issue then.
