### ISSUE TITLE
无法保存aria2设置的问题

### ISSUE THREAD

**Issue by ha7rock** [wahyd4/aria2-ariang-docker#38]
环境：群晖DS918+ Docker

通过ariang内进行的下载设置，如bittorrent的上传速率及做种时间。在docker重启容器之后 ，该类会复位。尝试了保存会话功能，但是看起来那并没有用。

求教如何保存设置，谢谢！

**Comment by wahyd4** [comment]
Basically due to AriaNg store all the configuration in the browser rather than change the actual configuration in Aria2, so if you didn't use the same browser or you have cleaned the cache, all the configuration will be gone.

It's more like a design approach rather than an issue, if you do wanna persist the change, you should modify the `aria2.conf` instead.
