### ISSUE TITLE
Aria2 session history lost after restarting docker container

### ISSUE THREAD

**Issue by Blood-Masr** [wahyd4/aria2-ariang-docker#45]
已經設置
檔案對應到， /app/conf/aria2.session。
但是每次 Docker重開，歷史紀錄還是不見了。
請問正確的檔案對應路徑 ?

**Comment by wahyd4** [comment]
Thanks for reporting this, this should be a bug, I will fix it later and keep you updated! Thanks.

By the way, please try to use English to describe the issue🙂

**Comment by Blood-Masr** [comment]
Log Information:
2019-07-24 16:10:11.010248 [ERROR] [SaveSessionCommand.cc:86] Failed to serialize session to '/app/conf/aria2.session'.

**Comment by yejiawei1234** [comment]
If I stop my container with unfinished file, when I restart my container there are lots of warning message. And I can not run my container again. 

The warning message are below:
chown: /data/._filename.mp4: Operation not permitted.

How can I delete all those unfinished files and restart my container?

**Comment by wahyd4** [comment]
@yejiawei1234  I am not sure the issue you mentioned is relevant to this one. Please create a new issue if you don't mind.

**Comment by wahyd4** [comment]
@Blood-Masr Good news! Just made it work by mount the `/app/conf` folder instead of mounting `/app/conf/aria2.session` separately.

There is a workable example below:
```bash
docker run -it -p 80:80 --name test  -v /Users/junv/data:/data -v /Users/junv/conf/:/app/conf  wahyd4/aria2-ui
```

Make sure in the `conf` folder on your host you have these two files exists:
- aria2.conf
- aria2.session

By the way, about mounting `/app/conf/aria2.session` standalone, I've tried a lot and I can see the user who runs aria2 inside the docker can actually access to the file I mounted, but it still doesn't work. I won't spend more time on this as the solution above is actually pretty neat.😀
